--
-- PostgreSQL database dump
--

\restrict wHOGlLaPCubJ64aheVRRTTDupjyymUjGvU7V1xViidWgFGBwEt17LJfmqNMiv3P

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public."Enrollments" DROP CONSTRAINT IF EXISTS "FK_Enrollments_Students_StudentId";
ALTER TABLE IF EXISTS ONLY public."Enrollments" DROP CONSTRAINT IF EXISTS "FK_Enrollments_Courses_CourseId";
ALTER TABLE IF EXISTS ONLY public."Courses" DROP CONSTRAINT IF EXISTS "FK_Courses_Teachers_TeacherId";
DROP INDEX IF EXISTS public."IX_Teachers_Email";
DROP INDEX IF EXISTS public."IX_Students_Email";
DROP INDEX IF EXISTS public."IX_Enrollments_StudentId_CourseId";
DROP INDEX IF EXISTS public."IX_Enrollments_CourseId";
DROP INDEX IF EXISTS public."IX_Courses_TeacherId";
ALTER TABLE IF EXISTS ONLY public."__EFMigrationsHistory" DROP CONSTRAINT IF EXISTS "PK___EFMigrationsHistory";
ALTER TABLE IF EXISTS ONLY public."Teachers" DROP CONSTRAINT IF EXISTS "PK_Teachers";
ALTER TABLE IF EXISTS ONLY public."Students" DROP CONSTRAINT IF EXISTS "PK_Students";
ALTER TABLE IF EXISTS ONLY public."Enrollments" DROP CONSTRAINT IF EXISTS "PK_Enrollments";
ALTER TABLE IF EXISTS ONLY public."Courses" DROP CONSTRAINT IF EXISTS "PK_Courses";
DROP TABLE IF EXISTS public."__EFMigrationsHistory";
DROP TABLE IF EXISTS public."Teachers";
DROP TABLE IF EXISTS public."Students";
DROP TABLE IF EXISTS public."Enrollments";
DROP TABLE IF EXISTS public."Courses";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Courses" (
    "Id" integer NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Description" character varying(1000),
    "Credits" integer NOT NULL,
    "TeacherId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Courses" OWNER TO postgres;

--
-- Name: Courses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Courses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Courses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Enrollments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Enrollments" (
    "Id" integer NOT NULL,
    "StudentId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    "EnrollmentDate" timestamp with time zone NOT NULL,
    "Grade" integer
);


ALTER TABLE public."Enrollments" OWNER TO postgres;

--
-- Name: Enrollments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Enrollments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Enrollments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Students" (
    "Id" integer NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "BirthDate" date NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Students" OWNER TO postgres;

--
-- Name: Students_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Students" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Students_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Teachers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Teachers" (
    "Id" integer NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Department" character varying(100) NOT NULL
);


ALTER TABLE public."Teachers" OWNER TO postgres;

--
-- Name: Teachers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Teachers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Teachers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Courses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Courses" ("Id", "Name", "Description", "Credits", "TeacherId", "CreatedAt") FROM stdin;
1	Web Services	REST API on ASP.NET Core	5	2	2026-09-28 06:19:54.530495+00
2	Databases	Relational databases and SQL	4	1	2026-09-28 06:19:54.5306+00
3	Algorithms	Data structures and algorithms	6	1	2026-09-28 06:19:54.530601+00
4	Information Systems	Design of information systems	3	3	2026-09-28 06:19:54.530601+00
\.


--
-- Data for Name: Enrollments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Enrollments" ("Id", "StudentId", "CourseId", "EnrollmentDate", "Grade") FROM stdin;
1	1	1	2026-09-28 06:19:54.556814+00	90
2	1	2	2026-09-28 06:19:54.556912+00	75
3	2	1	2026-09-28 06:19:54.556912+00	\N
4	3	3	2026-09-28 06:19:54.556913+00	82
\.


--
-- Data for Name: Students; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Students" ("Id", "FirstName", "LastName", "Email", "BirthDate", "CreatedAt") FROM stdin;
1	Alex	Smith	alex.smith@university.kz	2004-03-12	2026-09-28 06:19:54.507292+00
2	Anna	Ivanova	anna.ivanova@university.kz	2003-11-02	2026-09-28 06:19:54.507391+00
3	Max	Petrov	max.petrov@university.kz	2004-07-25	2026-09-28 06:19:54.507392+00
4	Dana	Kim	dana.kim@university.kz	2005-01-09	2026-09-28 06:19:54.507392+00
\.


--
-- Data for Name: Teachers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Teachers" ("Id", "FirstName", "LastName", "Email", "Department") FROM stdin;
1	Farida	Abdoldina	f.abdoldina@university.kz	Software Engineering
2	Evgeniy	Gertsen	e.gertsen@university.kz	Software Engineering
3	Aigul	Nurlanova	a.nurlanova@university.kz	Information Systems
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260928060827_InitialCreate	10.0.12
\.


--
-- Name: Courses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Courses_Id_seq"', 4, true);


--
-- Name: Enrollments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Enrollments_Id_seq"', 4, true);


--
-- Name: Students_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Students_Id_seq"', 4, true);


--
-- Name: Teachers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Teachers_Id_seq"', 3, true);


--
-- Name: Courses PK_Courses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "PK_Courses" PRIMARY KEY ("Id");


--
-- Name: Enrollments PK_Enrollments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Enrollments"
    ADD CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id");


--
-- Name: Students PK_Students; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Students"
    ADD CONSTRAINT "PK_Students" PRIMARY KEY ("Id");


--
-- Name: Teachers PK_Teachers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Teachers"
    ADD CONSTRAINT "PK_Teachers" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Courses_TeacherId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Courses_TeacherId" ON public."Courses" USING btree ("TeacherId");


--
-- Name: IX_Enrollments_CourseId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Enrollments_CourseId" ON public."Enrollments" USING btree ("CourseId");


--
-- Name: IX_Enrollments_StudentId_CourseId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Enrollments_StudentId_CourseId" ON public."Enrollments" USING btree ("StudentId", "CourseId");


--
-- Name: IX_Students_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Students_Email" ON public."Students" USING btree ("Email");


--
-- Name: IX_Teachers_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Teachers_Email" ON public."Teachers" USING btree ("Email");


--
-- Name: Courses FK_Courses_Teachers_TeacherId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "FK_Courses_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES public."Teachers"("Id") ON DELETE RESTRICT;


--
-- Name: Enrollments FK_Enrollments_Courses_CourseId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses"("Id") ON DELETE CASCADE;


--
-- Name: Enrollments FK_Enrollments_Students_StudentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES public."Students"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict wHOGlLaPCubJ64aheVRRTTDupjyymUjGvU7V1xViidWgFGBwEt17LJfmqNMiv3P

