services:
  db:
    image: postgres:17-alpine
    container_name: university-db
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - university-data:/var/lib/postgresql/data

volumes:
  university-data:
